apiVersion: v1
kind: Pod
metadata:
  name: user20-paralel2022-cuda11-devel
spec:
  restartPolicy: Never
  volumes:
    - name: paralel2022-pv-storage
      persistentVolumeClaim:
        claimName: paralel2022-pv-claim
  containers:
    - name: paralel2022-container
      image: "nvcr.io/nvidia/cuda:11.0.3-devel-ubi8"  # Change this (Look up at NGC NVIDIA)
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 10; done"]
      volumeMounts:
        - mountPath: "/myworkspace"
          name: paralel2022-pv-storage