apiVersion: v1
kind: Pod
metadata:
  name: user20-paralel2022-tensorflow
spec:
  restartPolicy: Never
  volumes:
    - name: paralel2022-pv-storage
      persistentVolumeClaim:
        claimName: paralel2022-pv-claim
  containers:
    - name: paralel2022-container
      image: "nvcr.io/nvidia/tensorflow:22.04-tf2-py3"  # Change this (Look up at NGC NVIDIA)
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 10; done"]
      volumeMounts:
        - mountPath: "/workspace"
          name: paralel2022-pv-storage